---
swagger: "2.0"
info:
  version: "2023-04-01T19:00:20Z"
  title: "photo-album-cloudformation-API"
host: "83do5batbh.execute-api.us-east-1.amazonaws.com"
basePath: "/s1"
schemes:
- "https"
paths:
  /search:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "q"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/SearchResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /upload/{bucket}/{key}:
    put:
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        required: true
        type: "string"
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      - name: "x-amz-meta-customLabels"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/UploadResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "bucket"
        in: "path"
        required: true
        type: "string"
      - name: "key"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  UploadResponse:
    type: "object"
  SearchResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          type: "object"
          properties:
            items:
              type: "string"
            url:
              type: "string"
            labels:
              type: "array"
